dofile(core.get_modpath("clans").."/spawning.lua")
dofile(core.get_modpath("clans").."/clans.lua")
dofile(core.get_modpath("clans").."/clans_commands.lua")
dofile(core.get_modpath("clans").."/kiwi_sea_test.lua")
dofile(core.get_modpath("clans").."/sacrifice.lua")